\" Permission to use, copy, modify, and/or distribute this software for
\" any purpose with or without fee is hereby granted.
\"
\" THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL
\" WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES
\" OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
\" FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY
\" DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
\" AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
\" OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
\"
\" true.1 - man page for true
.
.TH TRUE 1 "12 Dec 2025" neocore
.
.SH NAME
true \- return true value
.
.SH SYNOPSIS
.B true
[\fI\,--help \/\fR|\fI\, --version\/\fR]
\fI\,OPTION\/\fR...
.br
.
.SH DESCRIPTION
Exit with zero exit code.
.
.SH OPTIONS
.TP
\fB\-\-help\fR
display help message and exit
.TP
\fB\-\-version\fR
print version and exit
.TP
\fBOPTION\fR...
any other options will be ignored
.
.SH EXIT STATUS
.B true
always exits with zero exit code.
.
.SH STANDARTS
POSIX.1-2008
.
.SH AUTHORS
Written by gimura.
.
.SH SEE ALSO
\fBfalse\fP(1)
